[workspace]
resolver = "2"
members = [
    "crates/bio-core",
    "crates/bl-core",
    "crates/bl-lexer",
    "crates/bl-parser",
    "crates/bl-runtime",
    "crates/bl-seurat-compat",
    "crates/bl-bio",
    "crates/bl-apis",
    "crates/bl-compiler",
    "crates/bl-jit",
    "crates/bl-repl",
    "crates/bl-lsp",
    "crates/bl-language",
    "crates/bl-import",
    "crates/bl-cli",
    "crates/bl-fmt",
    "crates/bl-qc",
    "crates/bl-refs",
    "crates/bl-wasm",
    "crates/bl-convert",
]

[workspace.package]
version = "1.5.0"
edition = "2021"
license = "MIT"
authors = ["Raj Bandi <raj@oriclabs.com>"]
rust-version = "1.82"
repository = "https://github.com/oriclabs/biolang"
homepage = "https://lang.bio"
documentation = "https://lang.bio/docs"
description = "A pipe-first bioinformatics language with native DNA types and 1000+ builtins"
keywords = ["bioinformatics", "genomics", "dna", "pipe", "dsl"]
categories = ["science", "command-line-utilities"]

[workspace.dependencies]
bio-core = { path = "crates/bio-core" }
bl-core = { path = "crates/bl-core" }
bl-lexer = { path = "crates/bl-lexer" }
bl-parser = { path = "crates/bl-parser" }
bl-runtime = { path = "crates/bl-runtime", default-features = false }
bl-seurat-compat = { path = "crates/bl-seurat-compat" }
bl-bio = { path = "crates/bl-bio" }
bl-apis = { path = "crates/bl-apis" }
bl-compiler = { path = "crates/bl-compiler" }
bl-jit = { path = "crates/bl-jit" }
bl-repl = { path = "crates/bl-repl" }
bl-lsp = { path = "crates/bl-lsp" }
bl-language = { path = "crates/bl-language" }
bl-import = { path = "crates/bl-import" }
bl-cli = { path = "crates/bl-cli" }
bl-fmt = { path = "crates/bl-fmt" }
bl-qc = { path = "crates/bl-qc" }
bl-refs = { path = "crates/bl-refs" }
serde = { version = "1", features = ["derive"] }
